# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: abstractplay

plugins:
  - serverless-dotnet
  - serverless-aws-documentation
  - serverless-reqvalidator-plugin
  - serverless-domain-manager
  - serverless-plugin-warmup

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: dotnetcore2.0
  memorySize: 256
  timeout: 30
  versionFunctions: false

# you can overwrite defaults here
  stage: dev
  region: us-east-2

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  artifact: bin/release/netcoreapp2.0/deploy-package.zip
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  GraphQL:
    handler: abstractplay::abstractplay.Functions::GraphQL
    environment:
      db_server: ${file(../apsecrets.yml):db_server}
      db_database: ${file(../apsecrets.yml):db_database}
      db_username: ${file(../apsecrets.yml):db_username}
      db_password: ${file(../apsecrets.yml):db_password}
    vpc:
      securityGroupIds:
        - ${file(../apsecrets.yml):secGroup}
      subnetIds:
        - ${file(../apsecrets.yml):subnet1}
        - ${file(../apsecrets.yml):subnet2}
        - ${file(../apsecrets.yml):subnet3}
    events:
      - http:
          path: /graphql
          method: get
          reqValidatorName: 'xRequestValidateQuery'
          request:
            parameters:
              querystrings:
                query: true
          documentation:
            summary: "GraphQL entry point (read only)"
            description: "This is how clients are to request data from the service. It is read only! Changes are made through other endpoints."

  UsersPost:
    handler: abstractplay::abstractplay.Functions::UsersPost
    events:
      - http:
          path: /users
          method: post
          reqValidatorName: 'xRequestValidateBody'
          authorizer:
            arn: ${file(../apsecrets.yml):cognitoarn}
          documentation:
            summary: "Create new profile"
            description: "This is how you create a new profile"
            requestModels:
              "application/json": "RequestUsersPost"

#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
#    events:
#      - http:
#          path: users/create
#          method: get
#      - s3: ${env:BUCKET}
#      - schedule: rate(10 minutes)
#      - sns: greeter-topic
#      - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000
#      - alexaSkill: amzn1.ask.skill.xx-xx-xx-xx
#      - alexaSmartHome: amzn1.ask.skill.xx-xx-xx-xx
#      - iot:
#          sql: "SELECT * FROM 'some_topic'"
#      - cloudwatchEvent:
#          event:
#            source:
#              - "aws.ec2"
#            detail-type:
#              - "EC2 Instance State-change Notification"
#            detail:
#              state:
#                - pending
#      - cloudwatchLog: '/aws/lambda/hello'
#      - cognitoUserPool:
#          pool: MyUserPool
#          trigger: PreSignUp

#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
resources:
  Resources:
    xRequestValidateBody:
      Type: "AWS::ApiGateway::RequestValidator"
      Properties:
        Name: 'reqvalidator-body'
        RestApiId: 
          Ref: ApiGatewayRestApi
        ValidateRequestBody: true
        ValidateRequestParameters: false
    xRequestValidateQuery:
      Type: "AWS::ApiGateway::RequestValidator"
      Properties:
        Name: 'reqvalidator-params'
        RestApiId: 
          Ref: ApiGatewayRestApi
        ValidateRequestBody: false
        ValidateRequestParameters: true

#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"

custom:
  dotnet:
    slndir: sln/abstractplay
  customDomain:
    domainName: api.abstractplay.com
    basepath: ''
    stage: ${self:provider.stage}
    createRoute53Record: false
    endpointType: "edge"
  documentation:
    info:
      version: "1"
      title: "Abstract Play API"
      description: "The primary Abstract Play API"
      termsOfService: "https://www.abstractplay.com/terms"
    models:
      -
        name: "RequestUsersPost"
        description: "Required body content when POSTing to /users"
        contentType: "application/json"
        schema: ${file(models/request_users_post.json)}
      -
        name: "ResourceUser"
        description: "Format of a single user record"
        contentType: "application/json"
        schema: ${file(models/resource_user.json)}


